In [10]:
import pandas as pd

caminho_arquivo = r'\\wsl.localhost\Ubuntu\home\edcarlos\work_environment\datalake\landing\exportacao_2024.csv'
df = pd.read_csv(caminho_arquivo, sep=',')
df.head()

,cd_ncm,cd_unidade,cd_pais,sg_ufncm,cd_via,cd_urf,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao
0,94036000,11,245,sp,4,817600,8,425,20423,2024-04-01
1,87088000,11,493,sp,1,817800,418615,60355,470512,2024-11-01
2,2071400,10,173,sp,1,817800,94080,94080,237562,2024-03-01
3,90303390,11,158,mg,1,817800,10,12,1704,2024-04-01
4,40129090,10,158,sc,4,817700,26,26,950,2024-08-01

In [11]:
import pandas as pd

caminho_arquivo = r'\\wsl.localhost\Ubuntu\home\edcarlos\work_environment\datalake\raw_data\PAIS.csv'
df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')
df.head()

,CO_PAIS,CO_PAIS_ISON3,CO_PAIS_ISOA3,NO_PAIS,NO_PAIS_ING,NO_PAIS_ESP
0,0,898,ZZZ,Não Definido,Not defined,No definido
1,13,4,AFG,Afeganistão,Afghanistan,Afganistan
2,15,248,ALA,"Aland, Ilhas",Aland Islands,"Alans, Islas"
3,17,8,ALB,Albânia,Albania,Albania
4,20,724,ESP,"Alboran-Perejil, Ilhas","Alboran-Perejil, Islands","Alboran-Perejil, Islas"

In [12]:
arquivo_exp = r'\\wsl.localhost\Ubuntu\home\edcarlos\work_environment\datalake\landing\exportacao_2024.csv'
arquivo_pais = r'\\wsl.localhost\Ubuntu\home\edcarlos\work_environment\datalake\raw_data\PAIS.csv'

df = pd.read_csv(arquivo_exp, sep=',', encoding='latin') #padronização 
df_pais = pd.read_csv(arquivo_pais, sep=';', encoding='latin1')

df['cd_pais'] = df['cd_pais'].astype(str)
df_pais['CO_PAIS'] = df_pais['CO_PAIS'].astype(str)

df = df.merge(df_pais, left_on='cd_pais', right_on='CO_PAIS', how='left')
df.head()

,cd_ncm,cd_unidade,cd_pais,sg_ufncm,cd_via,cd_urf,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,CO_PAIS,CO_PAIS_ISON3,CO_PAIS_ISOA3,NO_PAIS,NO_PAIS_ING,NO_PAIS_ESP
0,94036000,11,245,sp,4,817600,8,425,20423,2024-04-01,245,724,ESP,Espanha,Spain,España
1,87088000,11,493,sp,1,817800,418615,60355,470512,2024-11-01,493,484,MEX,México,Mexico,México
2,2071400,10,173,sp,1,817800,94080,94080,237562,2024-03-01,173,174,COM,Comores,Comoros,Comoras
3,90303390,11,158,mg,1,817800,10,12,1704,2024-04-01,158,152,CHL,Chile,Chile,Chile
4,40129090,10,158,sc,4,817700,26,26,950,2024-08-01,158,152,CHL,Chile,Chile,Chile

In [13]:
df = df.drop(columns=['cd_pais', 'CO_PAIS', 'CO_PAIS_ISON3', 'CO_PAIS_ISOA3', 'NO_PAIS_ING', 'NO_PAIS_ESP'])
df.head()

,cd_ncm,cd_unidade,sg_ufncm,cd_via,cd_urf,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,NO_PAIS
0,94036000,11,sp,4,817600,8,425,20423,2024-04-01,Espanha
1,87088000,11,sp,1,817800,418615,60355,470512,2024-11-01,México
2,2071400,10,sp,1,817800,94080,94080,237562,2024-03-01,Comores
3,90303390,11,mg,1,817800,10,12,1704,2024-04-01,Chile
4,40129090,10,sc,4,817700,26,26,950,2024-08-01,Chile

In [14]:
# Caminho do arquivo
caminho_arquivo = r'\\wsl$\Ubuntu\home\edcarlos\work_environment\datalake\raw_data\URF.csv' #foi nomeado dessa forma porque não encontrou o arquivo porque está no wsl2
# Lendo o CSV para um DataFrame
df1 = pd.read_csv(caminho_arquivo, sep=';',  encoding='latin1')  # Ou tente 'ISO-8859-1'
# Exibir as primeiras linhas do DataFrame
df1.head()

   CO_URF                                             NO_URF
0     910  0000910 - SEFAZ-SC - CONVENIO CONSULTA SISTEMA...
1  110100                                 0110100 - BRASILIA
2  117600      0117600 - AEROPORTO INTERNACIONAL DE BRASILIA
3  120100                                  0120100 - GOIANIA
4  120102                                  0120102 - CATALAO

In [15]:
# Caminho do arquivo URF
arquivo_urf = r'\\wsl$\Ubuntu\home\edcarlos\work_environment\datalake\raw_data\URF.csv'

df_urf = pd.read_csv(arquivo_urf, sep=';', encoding='latin1')
df1 = df['cd_urf'] = df['cd_urf'].astype(str)
df_urf['CO_URF'] = df_urf['CO_URF'].astype(str)

df1 = df.merge(df_urf, left_on='cd_urf', right_on='CO_URF', how='left')
df1.head()

,cd_ncm,cd_unidade,sg_ufncm,cd_via,cd_urf,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,NO_PAIS,CO_URF,NO_URF
0,94036000,11,sp,4,817600,8,425,20423,2024-04-01,Espanha,817600,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1,87088000,11,sp,1,817800,418615,60355,470512,2024-11-01,México,817800,0817800 - PORTO DE SANTOS
2,2071400,10,sp,1,817800,94080,94080,237562,2024-03-01,Comores,817800,0817800 - PORTO DE SANTOS
3,90303390,11,mg,1,817800,10,12,1704,2024-04-01,Chile,817800,0817800 - PORTO DE SANTOS
4,40129090,10,sc,4,817700,26,26,950,2024-08-01,Chile,817700,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS

In [16]:
df2 = df1.drop(['cd_urf', 'CO_URF'], axis=1)
df2.head()

,cd_ncm,cd_unidade,sg_ufncm,cd_via,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,NO_PAIS,NO_URF
0,94036000,11,sp,4,8,425,20423,2024-04-01,Espanha,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1,87088000,11,sp,1,418615,60355,470512,2024-11-01,México,0817800 - PORTO DE SANTOS
2,2071400,10,sp,1,94080,94080,237562,2024-03-01,Comores,0817800 - PORTO DE SANTOS
3,90303390,11,mg,1,10,12,1704,2024-04-01,Chile,0817800 - PORTO DE SANTOS
4,40129090,10,sc,4,26,26,950,2024-08-01,Chile,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS

In [17]:
# Caminho do arquivo
caminho_arquivo = r'\\wsl$\Ubuntu\home\edcarlos\work_environment\datalake\raw_data\NCM.csv' #foi nomeado dessa forma porque não encontrou o arquivo porque está no wsl2
# Lendo o CSV para um DataFrame
df_ncm = pd.read_csv(caminho_arquivo, sep=';',  encoding='latin1')  # Ou tente 'ISO-8859-1'
# Exibir as primeiras linhas do DataFrame
df_ncm.head()

,CO_NCM,CO_UNID,CO_SH6,CO_PPE,CO_PPI,CO_FAT_AGREG,CO_CUCI_ITEM,CO_CGCE_N3,CO_SIIT,CO_ISIC_CLASSE,CO_EXP_SUBSET,NO_NCM_POR,NO_NCM_ESP,NO_NCM_ING
0,49011000,10,490110,3521.0,3521.0,3.0,89215,322,9000.0,5811,8099.0,"Livros, brochuras e impressos semelhantes, em ...","Libros, folletos, impresos similares, en hojas...","Books, brochures, similar printed papers, in s..."
1,49019100,10,490191,3521.0,3521.0,3.0,89216,322,9000.0,5811,8099.0,"Dicionários e enciclopédias, mesmo em fascículos","Diccionarios y enciclopedias, incluso en fascí...","Dictionaries and encyclopaedias, serial instal..."
2,49019900,10,490199,3521.0,3521.0,3.0,89219,322,9000.0,5811,8099.0,"Outros livros, brochuras e impressos semelhantes","Otros libros, folletos y impresos similares","Oth.printed books, brochures and similar printed"
3,49021000,10,490210,3521.0,3521.0,3.0,89221,322,9000.0,5813,8099.0,"Jornais e publicações periódicas, impressos, m...","Diarios y publicaciones, impresos, periodo>=4 ...","Newspapers, journals, printed, periodical>=4 t..."
4,52102910,10,521029,3840.0,3840.0,3.0,65251,240,4000.0,1312,1605.0,Tecidos de algodão que contenham menos de 85 %...,"Tejidos de algodón, blanqueados, con fibras si...","Fabrics of cotton, bleached, synthetic or arti..."

In [18]:
# Caminho do arquivo URF
arquivo_urf = r'\\wsl$\Ubuntu\home\edcarlos\work_environment\datalake\raw_data\NCM.csv'

# Carregar o arquivo que contém os códigos e nomes das URFs
df_ncm = pd.read_csv(arquivo_urf, sep=';', encoding='latin1')

df3 = df2['cd_ncm'] = df2['cd_ncm'].astype(str)
df_ncm['CO_NCM'] = df_ncm['CO_NCM'].astype(str)

df3 = df2.merge(df_ncm, left_on='cd_ncm', right_on='CO_NCM', how='left')
df3.head()

,cd_ncm,cd_unidade,sg_ufncm,cd_via,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,NO_PAIS,NO_URF,...,CO_PPI,CO_FAT_AGREG,CO_CUCI_ITEM,CO_CGCE_N3,CO_SIIT,CO_ISIC_CLASSE,CO_EXP_SUBSET,NO_NCM_POR,NO_NCM_ESP,NO_NCM_ING
0,94036000,11,sp,4,8,425,20423,2024-04-01,Espanha,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...,...,3341.0,3.0,82159,311,4000.0,3100,2500.0,Outros móveis de madeira,Los demás muebles de madera,Other wooden furniture
1,87088000,11,sp,1,418615,60355,470512,2024-11-01,México,0817800 - PORTO DE SANTOS,...,3450.0,3.0,78439,280,2000.0,2930,1002.0,Amortecedores de suspensão para tratores e veí...,Amortiguadores de suspensión p/tractores y veh...,Suspension shock-absorbers f/tractors and moto...
2,2071400,10,sp,1,94080,94080,237562,2024-03-01,Comores,0817800 - PORTO DE SANTOS,...,1990.0,1.0,01235,324,4000.0,1010,503.0,"Pedaços e miudezas, comestíveis de galos/galin...","Trozos y despojos comest.de gallo/gallina, con...","Fowls spec.gal.domest.cuts and offal, frozen"
3,90303390,11,mg,1,10,12,1704,2024-04-01,Chile,0817800 - PORTO DE SANTOS,...,3715.0,3.0,87475,110,1000.0,2651,2600.0,Outros aparelhos e instrumentos sem dispositiv...,Otros instrumentos y aparatos sin un dispositi...,Other instruments and appliances without a rec...
4,40129090,10,sc,4,26,26,950,2024-08-01,Chile,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS,...,3040.0,3.0,62594,280,3000.0,2211,1008.0,"Protetores, bandas de rodagem, etc, para pneus...","Protectores, bandas rodadura, etc.p/neumáticos...","Protecting, bands wheelwork, etc.fortires of r..."

In [19]:
df3 = df3.drop(columns=['cd_ncm', 'CO_PPI', 'CO_FAT_AGREG', 'CO_CUCI_ITEM', 'CO_CGCE_N3', 'CO_SIIT', 'CO_ISIC_CLASSE', 'CO_EXP_SUBSET', 'NO_NCM_ESP', 'NO_NCM_ING', 'CO_PPE', 'CO_NCM', 'CO_SH6', 'CO_UNID'])
df3.head()

,cd_unidade,sg_ufncm,cd_via,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,NO_PAIS,NO_URF,NO_NCM_POR
0,11,sp,4,8,425,20423,2024-04-01,Espanha,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...,Outros móveis de madeira
1,11,sp,1,418615,60355,470512,2024-11-01,México,0817800 - PORTO DE SANTOS,Amortecedores de suspensão para tratores e veí...
2,10,sp,1,94080,94080,237562,2024-03-01,Comores,0817800 - PORTO DE SANTOS,"Pedaços e miudezas, comestíveis de galos/galin..."
3,11,mg,1,10,12,1704,2024-04-01,Chile,0817800 - PORTO DE SANTOS,Outros aparelhos e instrumentos sem dispositiv...
4,10,sc,4,26,26,950,2024-08-01,Chile,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS,"Protetores, bandas de rodagem, etc, para pneus..."

In [20]:
df4 = df3.rename(columns={  
    'cd_unidade': 'cd_unidade',
    'sg_ufncm': 'sg_ufncm',
    'cd_via': 'cd_via',
    'qt_estatistica': 'qt_estatistica',
    'kg_liquido': 'kg_liquido',
    'vl_dolarfob': 	'vl_dolarfob',
    'data_exportacao': 'data_exportacao',
    'NO_PAIS': 'cd_pais',
    'NO_URF': 'cd_urf',
    'NO_NCM_POR': 'cd_ncm'
    
    })
df3.columns = df3.columns.str.strip().str.lower().str.replace(' ', '_')
df4.head()

,cd_unidade,sg_ufncm,cd_via,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,cd_pais,cd_urf,cd_ncm
0,11,sp,4,8,425,20423,2024-04-01,Espanha,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...,Outros móveis de madeira
1,11,sp,1,418615,60355,470512,2024-11-01,México,0817800 - PORTO DE SANTOS,Amortecedores de suspensão para tratores e veí...
2,10,sp,1,94080,94080,237562,2024-03-01,Comores,0817800 - PORTO DE SANTOS,"Pedaços e miudezas, comestíveis de galos/galin..."
3,11,mg,1,10,12,1704,2024-04-01,Chile,0817800 - PORTO DE SANTOS,Outros aparelhos e instrumentos sem dispositiv...
4,10,sc,4,26,26,950,2024-08-01,Chile,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS,"Protetores, bandas de rodagem, etc, para pneus..."

In [21]:
#deixei as linas das colunas com letras minúsculas
df4['cd_pais'] = df4['cd_pais'].str.lower()
df4['cd_urf'] = df4['cd_urf'].str.lower()
df4['cd_ncm'] = df4['cd_ncm'].str.lower()
df4.head()

,cd_unidade,sg_ufncm,cd_via,qt_estatistica,kg_liquido,vl_dolarfob,data_exportacao,cd_pais,cd_urf,cd_ncm
0,11,sp,4,8,425,20423,2024-04-01,espanha,0817600 - aeroporto internacional de sao paulo...,outros móveis de madeira
1,11,sp,1,418615,60355,470512,2024-11-01,méxico,0817800 - porto de santos,amortecedores de suspensão para tratores e veí...
2,10,sp,1,94080,94080,237562,2024-03-01,comores,0817800 - porto de santos,"pedaços e miudezas, comestíveis de galos/galin..."
3,11,mg,1,10,12,1704,2024-04-01,chile,0817800 - porto de santos,outros aparelhos e instrumentos sem dispositiv...
4,10,sc,4,26,26,950,2024-08-01,chile,0817700 - aeroporto internacional de viracopos,"protetores, bandas de rodagem, etc, para pneus..."

In [22]:
caminho = "/home/edcarlos/work_environment/datalake/silver/exportacao_2024_m.csv"
df4.to_csv(caminho, index=False)
print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!